# -*- coding: utf-8 -*-
"""role: a 10 year experience4d data scientist , hel...

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_oi5M_H00ejn8uWVEwPuaX_Xid2Kst0d

Welcome to the world of Data Science! As your mentor, I’m thrilled to guide you through building this Clinical Trial Disease Category Classification system. This is an excellent, high-impact project for your portfolio because it bridges the gap between raw textual medical data and actionable healthcare analytics.

Since you are a fresher tackling this as a college project, we are going to build this the *right way*—using enterprise-grade habits. You mentioned you want to use **PostgreSQL** and **SQLAlchemy** for your data layer, which is fantastic! Storing your raw and preprocessed data in a relational database, rather than just relying on loose CSV files, makes your project significantly more robust, scalable, and professional.

Here is your comprehensive, step-by-step implementation guide to ace this project within your 10-day timeline.

---

## Phase 1: Environment Setup & Database Architecture (Day 1)

Before diving into Natural Language Processing (NLP), we need to set up a solid foundation. We will configure a Python virtual environment and establish your database schema using SQLAlchemy.

### 1. Project Directory Structure

Keep your codebase modular and clean:

```text
clinical_trial_project/
│
├── data/                  # Local backup files
├── src/
│   ├── __init__.py
│   ├── database.py        # SQLAlchemy configuration and models
│   ├── pipeline.py        # Text preprocessing & ETL functions
│   └── train.py           # ML Model training and evaluation
│
├── app.py                 # Streamlit Web Application
├── requirements.txt       # Dependencies
└── README.md              # Documentation

```

### 2. SQLAlchemy Models (`src/database.py`)

Initialize your PostgreSQL connection and define your tables. You will need a table to hold the raw clinical trial data and another (or columns) to store the preprocessed text.
"""

from sqlalchemy import create_engine, Column, Integer, String, Text
from sqlalchemy.orm import declarative_base, sessionmaker

# Replace with your local PostgreSQL credentials
DATABASE_URL = "postgresql://username:password@localhost:5432/clinical_trials_db"

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autofield=False, bind=engine)
Base = declarative_base()

class ClinicalTrial(Base):
    __tablename__ = "clinical_trials"

    id = Column(Integer, primary_key=True, index=True)
    project_title = Column(String, nullable=True)
    brief_summary = Column(Text, nullable=False)  # Our target feature text
    cleaned_summary = Column(Text, nullable=True) # For preprocessed tokens
    disease_category = Column(String, nullable=True) # Target label

# Create tables in PostgreSQL
def init_db():
    Base.metadata.create_all(bind=engine)

"""---

## Phase 2: Data Ingestion & Storage (Day 2)

Your first data engineering task is to load the raw CSV data into your PostgreSQL database.

### Steps:

1. Download your dataset from the provided link.


2. Create an ingestion script that reads the CSV using Pandas.


3. Handle basic structural checks (column mapping, checking for completely empty summaries).


4. Use Pandas' `.to_sql()` method combined with your SQLAlchemy engine to push the data into your `clinical_trials` table seamlessly.

---

## Phase 3: Text Preprocessing Pipeline (Days 3-4)

Medical text is notoriously messy and full of dense terminology. To make it ready for a Machine Learning model, we have to clean and normalize it.

### The Text Cleaning Checklist:

* **Lowercase conversion:** Ensure `Cancer` and `cancer` are treated identically.
*
**Noise Removal:** Strip HTML tags, punctuation, special characters, and numbers using Python's `re` (Regular Expressions) library.


*
**Tokenization:** Break sentences down into individual words.


*
**Stop Word Removal:** Eliminate common words (`the`, `is`, `at`, `of`) that add zero medical context.


*
**Lemmatization:** Use `nltk` or `spaCy` to reduce words to their base root form (e.g., *"running"*, *"runs"*, *"ran"* $\rightarrow$ *"run"*; *"tumors"*, *"tumorless"* $\rightarrow$ *"tumor"*).



### Data Engineering Integration:

Pull the raw `brief_summary` records from PostgreSQL via an SQLAlchemy session, apply your preprocessing function, and write the tokens back into the `cleaned_summary` column. This ensures you don't have to keep reprocessing the text every time you tweak your ML model!

---

## Phase 4: Exploratory Data Analysis (EDA) (Day 5)

Before jumping into training, you must understand your data's patterns. Query your database, load the data back into a Pandas DataFrame, and use **Matplotlib**, **Seaborn**, or **Plotly** to visualize the following:

*
**Class Imbalance:** Plot a bar chart showing the distribution of your `disease_category` labels. *Are there 2,000 heart disease trials but only 50 rare genetic disease trials?* Knowing this tells you if you need to adjust class weights during training.


*
**Word Clouds / Frequency Plots:** Extract the top 20 most frequent words across different disease categories to make sure your lemmatization worked perfectly and that distinct keywords stand out for different classes.



---

## Phase 5: Feature Engineering & Model Training (Days 6-7)

Computers don't understand text; they understand numbers. We need to convert our text strings into a mathematical matrix.

### 1. Vectorization

Use Scikit-Learn’s **TF-IDF (Term Frequency-Inverse Document Frequency) Vectorizer**. TF-IDF is highly effective for text classification because it penalizes words that appear everywhere across the entire dataset while rewarding terms unique to specific documents (like specific drug names or medical conditions).

### 2. Model Selection

Don't jump straight into massive deep learning models. Start with robust, reliable classification baselines:

* **Logistic Regression:** Surprisingly powerful for high-dimensional TF-IDF features.
* **Multinomial Naive Bayes:** A classic text classification baseline.
* **Random Forest / Linear SVM:** Great for handling non-linear patterns or clean boundaries.

### 3. Training & Evaluation Pipeline

Split your data into an 80/20 train/test split. Train your models and evaluate them using key classification metrics:


$$Accuracy = \frac{\text{True Positives} + \text{True Negatives}}{\text{Total Samples}}$$

Generate a Scikit-Learn `classification_report` showing **Precision**, **Recall**, and **F1-Score** for every single disease category to prove your system's efficacy. Save your best-performing trained model and your fitted TF-IDF vectorizer using `pickle` or `joblib` so your web app can use them later.

---

## Phase 6: Interactive Streamlit Application (Days 8-9)

Now, let's bring your backend to life by building an interactive dashboard using **Streamlit**.

### Key Features to Implement:

1.
**Single Text Predictor:** Provide a large text area box where a user can paste an entirely new, raw clinical trial summary. Behind the scenes, your app will clean the text, transform it via your saved TF-IDF vectorizer, run it through your trained ML model, and display the predicted disease category instantly.


2.
**Database Dashboard:** Use SQLAlchemy inside Streamlit to pull stats live from your PostgreSQL database. Show beautiful Plotly charts of the current dataset distributions and metrics summary.



---

## Phase 7: Final Polish & Documentation (Day 10)

On your final day, clean up your repository and prepare your deliverables:

*
**Code Review:** Ensure all functions are commented properly and parameters aren't hardcoded.


*
**README.md:** Write clear instructions on how to set up the database, run the preprocessing script, train the model, and launch the Streamlit application.



---

## 💡 Quick Tips from Your Mentor

*
**Keep an eye out for a trap in the instructions:** Look closely at the problem statement provided in your guidelines doc. Notice that sources 10 through 15 accidentally mention "mobile product data", "clustering users", and "product recommendation systems". **Ignore those specific lines completely.** This happens sometimes when project briefs are adapted from older templates! Your actual objective, approach, and deliverables are 100% focused on **medical text NLP, TF-IDF, and supervised disease classification**. Don't accidentally write a recommendation system!


*
**Utilize your resources:** Remember that your learning platform hosts regular **Project Doubt Clarification Sessions** from Monday to Saturday between **3:30 PM and 4:30 PM IST** if you get stuck on an active bug or database connectivity issue.


*
**Prepare for evaluation:** Once everything is up and running, you can schedule your **Live Evaluation Session** via the booking form link. Note that the slot booking form only opens on weekends starting Saturday after 2:00 PM.



You've got a fantastic, structurally sound plan here. Take it step-by-step, build your database layer first, and watch how smoothly everything falls into place. Which section of the setup or text-cleaning pipeline would you like to start writing code for first?
"""